enum HttpStatusCodes {
    OK = 200,
    CREATED = 201,
    NO_CONTENT = 204,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    TOO_MANY_REQUESTS = 429,
    INTERNAL_SERVER_ERROR = 500
};

enum EndpointsContext {
    LOGIN = "LOGN",
    GET_ALL_CATEGORIES = "GACT",
    GET_CATEGORY_BY_ID = "GCBI",
    MODIFY_CATEGORY_BY_ID = "MCBI",
    CREATE_CATEGORY = "CRCT",
    GET_ALL_AUCTIONS = "GAAU",
    GET_AUCTION_BY_ID = "GABI",
    CREATE_AUCTION = "CRAU",
    CREATE_USER = "CRUS",
    GET_USER_SALES = "GUSA",
    GET_COMPLETED_AUCTIONS = "GCOA",
    GET_USER_AUCTIONS = "GUAU",
    CREATE_BLOCK_USER = "CRBU",
}

enum UserRoles {
    CUSTOMER = "CUSTOMER",
    AUCTIONEER = "AUCTIONEER",
    MODERATOR = "MODERATOR"
};

enum AuctionStatus {
    PROPOSED = "PROPUESTA",
    PUBLISHED = "PUBLICADA",
    REJECTED = "RECHAZADA",
    CLOSED = "CERRADA",
    CONCRETIZED = "CONCRETADA",
    FINISHED = "FINALIZADA"
}

export {
    HttpStatusCodes,
    UserRoles,
    AuctionStatus
};